[package]
name = "queueing-party"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
prometheus-client = "0.22.3"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_xoshiro = "0.6.0"
